apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
  name: eck
  namespace: default
spec: 
  ingressClassName: nginx
  tls:
  - hosts: 
    - "{{dns_hostname}}"  # Replace with actual DNS hostname 
    secretName: tls-secret-key
  rules:
    - host: "{{dns_hostname}}"  # Replace with actual DNS hostnamee
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601 
