apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.16.1  
  elasticsearchRef:
    name: elasticsearch
  enterpriseSearchRef:
    name: enterprise-search
