apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-main
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eramons/eck-lab.git'
    targetRevision: HEAD
    path: k8s/elasticsearch/main
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

