apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.1.2 
  count: 1
  elasticsearchRef:
    name: elasticsearch  # Reference to the Elasticsearch cluster
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi  # Minimum memory request for Kibana
              cpu: 1       # Minimum CPU request for Kibana
            limits:
              memory: 1Gi  # Maximum memory limit for Kibana
              cpu: 1       # Maximum CPU limit for Kibana
  http:
    service:
      spec:
        type: ClusterIP
#        type: NodePort  # Expose kibana on node port 30001
#        ports:
#          - name: http
#            protocol: TCP
#            port: 5601
#            nodePort: 30001
    tls:
      selfSignedCertificate:
        disabled: true
