apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.1.2 
  count: 1
  elasticsearchRef:
    name: elasticsearch  # Reference to the Elasticsearch cluster
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi  # Minimum memory request for Kibana
              cpu: 0.5    # Minimum CPU request for Kibana
            limits:
              memory: 1Gi  # Maximum memory limit for Kibana
              cpu: 0.5    # Maximum CPU limit for Kibana
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
